# Generated by Django 3.1.2 on 2020-11-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroidCount',
            fields=[
                ('id_centroid_count', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.SmallIntegerField(blank=True, null=True)),
                ('centroid', models.SmallIntegerField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'centroid_count',
                'ordering': ['id_observation'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id_observation', models.SmallAutoField(primary_key=True, serialize=False)),
                ('observation', models.CharField(blank=True, max_length=37, null=True)),
            ],
            options={
                'db_table': 'observation',
                'ordering': ['id_observation'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ypixels',
            fields=[
                ('id_ypixels', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.SmallIntegerField(blank=True, null=True)),
                ('ypixels', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ypixels',
                'ordering': ['id_observation', 'step'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='observation_selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
