#  Workflow to deploy the application to our VM. This only runs after a merge to master

name: deploy the application

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  cd:
    runs-on: ubuntu-latest
if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2
    - name: Build the Application
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: deploy
      run: |
        pytest
