# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: deploy the application

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  cd:
    runs-on: ubuntu-latest
if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2
    - name: Build the Application
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: deploy
      run: |
        pytest
